title: Mikes Pages
description: Mikes personal pages.

# Using a supported theme.
#theme: jekyll-theme-cayman

# Using another Jekyll theme hosted on GitHub.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false
