title: Mikes Pages
description: Mikes personal pages.
#author:
#  name: Mike Lake
#  email: mikel@speleonics.com.au

baseurl: ""
github_username: speleolinux

# Using a supported theme.
#theme: jekyll-theme-cayman
theme: minima

minima:
  skin: classic
  date_format: "%Y-%m-%d"
  social_links:
    - { platform: github,  user_url: "https://speleolinux.github.io" }

# Using Jekyll themes hosted on GitHub.
# For "minimal" set plugins: jekyll-remote-theme
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/leap-day@v0.2.0
#remote_theme: rundocs/jekyll-rtd-theme

#plugins:
#  - jekyll-remote-theme

# For minimal theme
#show_downloads: false

